greenplanet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from plants import views 

urlpatterns = [
    path('signup/', include('users.urls')),
    path('', auth_views.LoginView.as_view( template_name='users/signin.html'), name='sign_in'), 
    path('signout/', auth_views.LogoutView.as_view( template_name='users/signout.html'), name='sign_out'),
    path('plants/', include('plants.urls')),
    path('admin/', admin.site.urls),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),
]

plants/urls.py
from django.urls import path 
from . import views 

app_name = 'plants'

urlpatterns = [ 
    path('', views.index, name='index'),
    path('<int:plant_id>/', views.show, name='show'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('add_plant/', views.add_plant, name='add_plant'),
    ]

users/urls.py
from django.urls import path 
from . import views 
app_name = 'users' 
urlpatterns = [ 
    path('', views.sign_up, name='sign_up'), 
    ]

plants/models.py
from django.db import models

# Create your models here.
class Plant(models.Model): # each class variable represents a database i.e. table field in the model 
    name = models.CharField(max_length=200) 
    country = models.CharField(max_length=50) 
    climate = models.CharField(max_length=200) 
    soil = models.CharField(max_length=200) 
    family = models.CharField(max_length=200)
    height = models.FloatField()
    user_id = models.CharField(max_length=100, null=True)
    
    def __str__(self): 
        return self.name + "- " + self.country

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms 
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm 
from django.core import validators

class UserSignUpForm(UserCreationForm): 
    email = forms.EmailField(validators=[validators.validate_email]) 
    
    min_length = 2 
    max_length = 30 
    message_lt_min = f"Should have at least {min_length} characters." 
    message_ht_max = f"Should have at most{max_length} characters." 
    name_regex='\A[a-zA-Z]+\Z' 
    name_message='The name accepts only letters!'
    
    first_name = forms.CharField(validators=[ 
        validators.MinLengthValidator(min_length, message_lt_min), 
        validators.MaxLengthValidator(max_length, message_ht_max), 
        validators.RegexValidator(name_regex, name_message) ]) 
    last_name = forms.CharField(validators=[ 
        validators.MinLengthValidator(min_length), 
        validators.MaxLengthValidator(max_length), 
        validators.RegexValidator(name_regex, name_message) ]) 
    
    class Meta: 
        model = User 
        fields = ['username', 'first_name', 'last_name','email', 'password1', 'password2']

plants/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.http import Http404
from .models import Plant
from django.contrib.auth import login, authenticate , logout
from django.contrib import messages
# Create your views here. 
def index(request):
    if request.user.is_authenticated:
        current_user=request.user
        tallest_plants = Plant.objects.order_by('-height')[:15] 
        context = {'tallest_plants': tallest_plants} 
        return render(request, 'plants/index.html', context)
    else:
        return redirect("/")
        
# Create your views here.
def show(request, plant_id):
    if request.user.is_authenticated:
        current_user=request.user
        try: 
            plant = Plant.objects.get(pk=plant_id)
            print(plant); 
        except Plant.DoesNotExist: 
            raise Http404("Plant does not exist") 
        return render(request, 'plants/show.html', {'plant': plant})
    else:
        return redirect("/")
    
def add_plant(request):
    if request.user.is_authenticated:
        current_user=request.user
        if request.method == "POST":
            name = request.POST.get("name")
            country = request.POST.get("country")
            climate = request.POST.get("climate")
            soil = request.POST.get("soil")
            family = request.POST.get("family")
            height = request.POST.get("height")
            user_id = request.POST.get("user_id")
            print(name,country,climate,soil,family,height,user_id) 
            query=Plant(name=name,country=country,climate=climate,soil=soil,family=family,height=height,user_id=user_id) #We called here our class function "Plant" from model.py.
            query.save() #This is to save the particular Data that we are entering to be stored in DB
            messages.info(request,"New Plant data Inserted Successfully")
            return redirect("/plants")
        return render(request, 'plants/add_plant.html' , {'current_user': current_user})
    else:
        return redirect("/")
        
def update(request,id):
    if request.user.is_authenticated:
        current_user=request.user
        try:
            if request.method=="POST":
                name=request.POST['name']
                country=request.POST['country']
                climate=request.POST['climate']
                soil=request.POST['soil']
                family=request.POST['family']
                height=request.POST['height']
            
                edit = Plant.objects.get(id=id)
                edit.name = name
                edit.country = country
                edit.climate = climate
                edit.soil = soil
                edit.family = family
                edit.height = height
                edit.save()
                messages.warning(request,"Plant Data Updated Successfully")
                return redirect("/plants")
            
            plant = Plant.objects.get(pk=id)
        
        except Plant.DoesNotExist: 
            raise Http404("Plant does not exist") 
        return render(request, 'plants/update_plant.html' ,{'plant': plant})
    else:
        return redirect("/")
    
def delete(request,id):
    if request.user.is_authenticated:
        current_user=request.user
        context ={}
        plant = Plant.objects.get(id=id)
 
 
        if request.method =="POST":
            plant.delete()
            messages.error(request,"Plant Data Deleted Successfully")
            # after deleting redirect to Plant
            return redirect("/plants")
 
        return render(request, "plants/delete_plant.html", context)
    else:
        return redirect("/")

users/views.py
from django.shortcuts import render, redirect 
from django.contrib import messages 
from .forms import UserSignUpForm

# Create your views here.
def sign_up(request): 
    if request.method == "POST": 
        form = UserSignUpForm(request.POST) 
        if form.is_valid(): 
            form.save() 
            un = form.cleaned_data.get('username') 
            messages.success(request, 'Account has been successfully created for {}!'.format(un)) 
            return redirect('sign_in') 
    elif request.method == "GET": 
        form = UserSignUpForm() 
    return render(request, 'users/signup.html', {'form': form})

plants/templates/plants/add_plant.html
{% extends "plants/base_generic.html" %} 
{% block content %}
<form method="POST" class="post-form form_allignment" >  
        {% csrf_token %}  
        <div class="input-group mb-3">
        <label>Plant Name
          <input type="text" required="required" class="form-control" placeholder="Plant Name" name="name">
        </div>
        
        <div class="input-group mb-3">
        <label>Country
          <input type="text" required="required" class="form-control" placeholder="Enter the Country it is found in..." name="country">
        </label>
        </div>
        
        <div class="input-group mb-3">
        <label>Climate
          <input type="text" required="required" class="form-control" placeholder="Enter the suitable Climate for its growth" name="climate">
        </div>
        
        <div class="input-group mb-3">
        <label>Soil
          <input type="text" required="required" class="form-control" placeholder="Enter the soil suited for their growth" name="soil">
        </div>
        
        <div class="input-group mb-3">
        <label>Family
          <input type="text" required="required" class="form-control" placeholder="Name the Family it belongs to" name="family">
        </div>
        
        <div class="input-group mb-3">
        <label>Height
          <input type="number" required="required" class="form-control" placeholder="Please enter the avg height of the plant" name="height">
        </div>
        <input type="hidden" name="user_id" value="{{ current_user.id }}"/>
        
        <input type="submit" class="btn btn-outline-success" value="Submit"/>
    </form>
    {% endblock content %}

plants/templates/plants/base_generic.html
{% load static %} 
<!DOCTYPE html> 
<html> 
<head> 
    <link rel="stylesheet" href="{% static '/styles.css' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head> 
<body> 
    <header>
        <div class="heading"><a> Web Botanica</a></div>
        <nav>
            <ul class="nav_links">
                {% if user.is_authenticated %}
                <div class="barlinks">
                <li><a href="/plants">Plants</a></li>
                <li><a href="/plants/add_plant">Add Plant</a></li>
                </div>
                {% endif %}
            </ul>
        </nav>
        <div class="signin_button">
            {% if user.is_authenticated %} 
                <div class="greetings"> Welcome! {{user.username}}... 
                <a href="{% url 'sign_out' %}"><button>Sign Out</button></a> 
            {% else %} 
                <a href="{% url 'sign_in' %}"><button>Sign In</button></a>
            {% endif %}
            
        </div>
        
        <!--<div class="topnav"> 
            <a class="active" href="/">Home</a> | 
            {% if user.is_authenticated %} 
                <div> You are signed in as {{user.username}}... 
                <a href="{% url 'sign_out' %}">Sign out</a> 
            {% else %} 
                <a href="{% url 'sign_in' %}">Sign in</a> | 
                <a href="{% url 'users:sign_up' %}">Sign up</a> 
            {% endif %} 
        </div> -->
    </header> 
    <main> 
        {% block content %}{% endblock %} 
    </main> 
</body> 
</html>

plants/templates/plants/delete_plant.html
{% extends "plants/base_generic.html" %} 
{% block content %}
<form method="POST">
        {% csrf_token %}
        <div>
        Are you sure you want to delete this item ?
        <input type="submit" value="Yes" />
        <a href="/plants">Cancel </a>
        </div>
    </form>
{% endblock content %}

plants/templates/plants/index.html
{% extends "plants/base_generic.html" %} 
{% block content %}
<img class="banner" src="https://cdn.pixabay.com/photo/2018/08/21/23/29/forest-3622519_1280.jpg" alt="Forest">
<h1 class="text-center mt-3">Plants / Trees<h1> 
<h4 class="text-center mt-3">Displaying the list in descending order on the basis of their avg height</h4>

<div class="data-1">
{% if tallest_plants %} 
<ul class="list-group">
    {% for plant in tallest_plants %} 
  <li class="list-group-item"><a href="{% url 'plants:show' plant.id %}">{{ plant.name }}</a></li>
  {% endfor %} 
</ul>
{% else %} 
    <p>There are no plants recorded.</p> 
{% endif %}

</div>
   
{% endblock content %}

plants/templates/plants/show.html
{% extends "plants/base_generic.html" %} 
{% block content %}
<img class="banner" src="https://cdn.pixabay.com/photo/2017/01/30/16/11/sunset-2021266_1280.jpg" alt="Forest">

<div class="content container"> 
<h2 class="text-center">{{plant.name}} Details</h2> 
<table class="table ">
     <thea > 
     </thead> 
     <tbody> 
         <tr> 
             <td><b>Country:</b></td> 
             <td>{{plant.country}}</td> 
         </tr> 
         <tr> 
             <td><b>Climate:</b></td> 
             <td>{{plant.climate}}</td> 
         </tr> 
         <tr> 
             <td><b>Soil:</b></td> 
             <td>{{plant.soil}}</td> 
         </tr> 
         <tr> 
             <td><b>Family:</b></td> 
             <td>{{plant.family}}</td> 
         </tr>
         <tr> 
             <td><b>Height (feet):</b></td> 
             <td>{{plant.height}}</td> 
         </tr>
     </tbody> 
 </table>

 <a class="btn btn-success" href="/update/{{ plant.id }}">Update</a>
 <a class="btn btn-danger" href="/delete/{{ plant.id }}">Delete</a>
 
 </div>
 {% endblock content %}

plants/templates/plants/update_plant.html
{% extends "plants/base_generic.html" %} 
{% block content %}
<form method="POST" class="post-form form_allignment" >  
        {% csrf_token %}  
        <div class="input-group mb-3">
        <label>Plant Name
          <input type="text" required="required" class="form-control" placeholder="Plant Name" name="name" value="{{plant.name}}">
        </div>
        
        <div class="input-group mb-3">
        <label>Country
          <input type="text" required="required" class="form-control" placeholder="Enter the Country it is found in..." name="country" value="{{plant.country}}">
        </label>
        </div>
        
        <div class="input-group mb-3">
        <label>Climate
          <input type="text" required="required" class="form-control" placeholder="Enter the suitable Climate for its growth" name="climate" value="{{plant.climate}}">
        </div>
        
        <div class="input-group mb-3">
        <label>Soil
          <input type="text" required="required" class="form-control" placeholder="Enter the soil suited for their growth" name="soil" value="{{plant.soil}}">
        </div>
        
        <div class="input-group mb-3">
        <label>Family
          <input type="text" required="required" class="form-control" placeholder="Name the Family it belongs to" name="family" value="{{plant.family}}">
        </div>
        
        <div class="input-group mb-3">
        <label>Height
          <input type="number" required="required" class="form-control" placeholder="Please enter the avg height of the plant" name="height" value="{{plant.height}}">
        </div>
        <input type="hidden" name="user_id" value="{{ current_user.id }}"/>
        
        <input type="submit" class="btn btn-outline-success" value="Update"/>
    </form>
    {% endblock content %}

users/templates/users/signin.html
{% extends "plants/base_generic.html" %} 
{% block content %}
{% if user.is_authenticated %} 
    <div class="text_center"> <p>You are signed in {{user.username}}... 
        Go to... <a href="plants">Plants List</a></p>
        <p>Or add Plants <a href="/plants/add_plant">Add Plants</a></p>
{% else %}
    <h2 class="text_center">Welcome to the encyclopedia Scholars and Enthusiast!</h2>
    <form class=" signin-form" method="POST"> 
        {% csrf_token %} 
        {{ form.as_p }} 
        <div> 
            <button class="btn btn-success" type="submit">Sign In</button> 
        </div> 
        <p></p> 
        <div> If you don't have an account yet 
            <a href="{% url 'users:sign_up' %}">Sign Up</a> 
        </div> 
    </form>
{% endif %}
{% endblock content %}

users/templates/users/signout.html
{% extends "plants/base_generic.html" %} 
{% block content %}
<div class="text_center">You have been signed out.<div> 
<div class="text_center"><a href="{% url 'sign_in' %}">Sign In</a><div>
{% endblock content %}

users/templates/users/signup.html
{% extends "plants/base_generic.html" %} 
{% block content %}
<form class="form_allignment" method="POST"> 
    {% csrf_token %} 
    {{ form.as_p }} 
    <div> 
        <button type="submit">Sign Up</button> 
    </div> 
    <p></p> 
    <div> If you have an account 
    <a href="{% url 'sign_in' %}">Sign In</a> 
    </div> 
</form>
{% endblock content %}